### ISSUE TITLE
The first step of the Signature Generator doesn't work

### ISSUE THREAD

**Issue by AndreLovichi** [360Learning/360learning.github.io#11]
## Context
 - The Signature Generator was designed to help 360Learners to generate a beautiful branded signature for their GMail account
    - It's part of the onboarding, as last activity of the [Inbox 0 course](https://team.360learning.com/course/play/5ace26c636aec10d418de7d6)
 - But the first step of this tool doesn't work anymore: when the user clicks on "GENERATE THE SIGNATURE", nothing happens.

### Video recording
https://www.loom.com/share/b67d974a39e44c17af3d989daec8e877

**Comment by yev-kanivets** [comment]
@FabriceGaudin hello, I guess that the first step doesn't work because of a few reasons:
- it targets MOOC which is disabled now
- it uses [unsafe API](https://github.com/360Learning/backend/blob/91134d8efd5f573464989e1936bb6d5865d354b7/modules/webext/routes.js#L25) which is probably disabled by the Security team

![image](https://user-images.githubusercontent.com/11427267/235603684-94970802-9378-4d4f-8f2c-52900b62cb0e.png)

I suggest that we simply remove it from the Signature Generator to not mislead people using it. WDYT?

**Comment by FabriceGaudin** [comment]
@yev-kanivets Totally agree, let's remove it!
This step is only a nice-to-have and it makes the signature generator harder to maintain. The ROI is quite low, let's not overengineer.
Can you take care of removing it as well please? I can take care of the functional review if you want (easy part haha)

**Comment by yev-kanivets** [comment]
@FabriceGaudin it's done, you can review it on the PR above ⬆️

**Comment by FabriceGaudin** [comment]
@yev-kanivets The PR looks good! If you want I can do a functional review once it's merged (since it's not critical)

**Comment by yev-kanivets** [comment]
@FabriceGaudin it's merged and live, thanks 🙏

**Comment by FabriceGaudin** [comment]
@yev-kanivets Perfect! Thank you for your efficient help 💪
