### ISSUE TITLE
Update Signature Generator with new branding

### ISSUE THREAD

**Issue by martalx** [360Learning/360learning.github.io#20]
@FabriceGaudin cc @jeremybenzakein 

This feature should be ready beginning September.

The structure is exactly the same, only the design will change.

**OLD DESIGN**
<img width="456" alt="Capture d’écran 2023-03-13 à 12 58 1" src="https://user-images.githubusercontent.com/3406682/228531763-3e1d3408-2798-43f5-bcff-f1f03d426530.png">

**NEW DESIGN**
<img width="800" alt="EmailSIG_templateOverpass" src="https://user-images.githubusercontent.com/3406682/228535069-e5061e9f-64b8-4b0c-a5a2-5a750dd4ae8d.png">

- I don't know if is possible to use overpass on this since is a Google Font. But If not, Helvetica or Arial can be the alternatives

<img width="800" alt="EmailSIG_template" src="https://user-images.githubusercontent.com/3406682/228535236-b244b6ef-5e79-43f7-a0a0-9e0ab591a236.png">

All Assets are in this .zip (background, social media icons) the picture will be the same as the email account like today. I have another website to do the green ring and replace the gradient.

LMK if you need anything else: 

**Assets:** [assets.zip](https://github.com/360Learning/360learning.github.io/files/11100893/assets.zip)

**Figma File:** https://www.figma.com/file/4XPqSIJOB9BfbIKptz5jqK/%E2%9A%A0%EF%B8%8F-WIP---New-Brand-Guidelines?node-id=8%3A5&t=reaNKAwWzLWT785E-1

PS: All images were exported x2 to have more quality for retina screens. however, the format is the one on figma: 800x320px

**Comment by yev-kanivets** [comment]
@martalx hey, I've updated the branding in https://github.com/360Learning/360learning.github.io/pull/21. It's not yet merged, so you won't see the updates on https://360learning.github.io/signatureGenerator.html yet. I want to make sure that the updates are correct first.

Here is a screenshot of the signature after my updates:

<img width="1032" alt="Capture d’écran 2023-05-02 à 07 56 08" src="https://user-images.githubusercontent.com/11427267/235591139-5fb204ae-5a40-4e4b-8ba9-7e25e06d787d.png">

Is it correct that the signature size shouldn't change (be the same as the previous one)? I'm asking because the size of the Figma layout doesn't match that of the HTML (1.75x bigger approx.). That's why I needed to update sizes (font size, padding, etc.) on the eye. So feel free to ask me to move something a few pixels right/left/top/down or increase/decrease some sizes.

If you want to test the generator yourself, you can do it by:
- downloading [this zip](https://github.com/360Learning/360learning.github.io/files/11370186/360tools.zip)
- unzipping it locally on your computer
- clicking on `signatureGenerator.html`

The resulting signature won't be usable in Gmail though, because updated images (social icons, background) aren't yet merged and hosted in this repository. This issue will be resolved right after https://github.com/360Learning/360learning.github.io/pull/21 is merged.
